language: r
r:
    - devel
    - release
sudo: false
cache: packages

env:
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

addons:
  apt:
    packages:
    - texlive-latex-extra

notifications:
  email:
    on_success: change
    on_failure: change

r_binary_packages:
  - ggplot2
  - reshape
  - testthat
  - knitr
  - memisc
  - sp
  - arm
  - data.table
  - vcd
  - maptools
  - stringr
  - maptools
  - covr
  - lintr

after_success:
  - Rscript -e 'library(covr);coveralls()'
  
branches:
  only: master