language: r
sudo: required

env:
  global:
    - WARNINGS_ARE_ERRORS=1
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

before_install:
  - sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -q
  - sudo apt-get install -q libgeos-dev libgeos-3.4.2

notifications:
  email:
    on_success: change
    on_failure: change

r_binary_packages:
  - ggplot2
  - reshape
  - testthat
  - knitr
  - rgeos
  - arm
  - data.table
  - vcd
  - maptools
  - stringr
  - maps
  - sp
  - mapproj

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
after_success:
  - Rscript -e 'library(covr);coveralls()'